drop table if exists userinfo cascade
drop table if exists userinfo cascade
drop table if exists userinfo cascade
drop table if exists userinfo cascade
drop table if exists userinfo cascade
drop table if exists userinfo cascade
drop table if exists userinfo cascade
drop table if exists userinfo cascade
drop table if exists userinfo cascade
drop table if exists userinfo cascade
